# numpy tutorial

In [22]:
import numpy as np

### intro to numpy

In [2]:
a = np.array([1,2,3])
print(type(a),a.shape,a[0],a[1],a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [15]:
three = np.array([[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]])
print(three.shape)

(3, 3, 3)


### numpy functions to create arrays

In [6]:
c = np.zeros((2,2))
print(c)

[[0. 0.]
 [0. 0.]]


In [21]:
d = np.ones((1,2), dtype=int)
print(d)

[[1 1]]


In [16]:
e = np.full((2,2),7)
print(e)

[[7 7]
 [7 7]]


In [17]:
f = np.eye(2)
print(f)

[[1. 0.]
 [0. 1.]]


In [18]:
g = np.random.random((2,2))
print(g)

[[0.15115354 0.64505104]
 [0.37939197 0.90131259]]


### array indexing / slicing

In [26]:
h = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(h)
i = h[:2, 1:3] # a : b --> including a, excluding b (a --> b-1)
print(i)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [25]:
print(h[0,1])
i[0,0] = 77
print(h[0,1])

2
77


In [33]:
j = np.array([[1,2],[3,4],[5,6]])
print(j)
bool_index = (j > 2)
print(bool_index)
print(bool_index.dtype)
print(type(bool_index))

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
bool
<class 'numpy.ndarray'>


In [32]:
print(j[bool_index])
print(j[j > 2])

[3 4 5 6]
[3 4 5 6]


### datatypes

In [34]:
x = np.array([1,2])
y = np.array([1.0,2.0])
z = np.array([1,2], dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


### array math

In [38]:
k = np.array([[1,2],[3,4]], dtype=np.float32)
l = np.array([[5,6],[7,8]], dtype=np.float)
print(k.dtype, l.dtype)
print(k+l)
print(np.add(k,l))

float32 float64
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [39]:
print(k-l)
print(np.subtract(k,l))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [40]:
print(k*l)
print(np.multiply(k,l))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [41]:
print(k/l)
print(np.divide(k,l))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [42]:
print(np.sqrt(k))

[[1.        1.4142135]
 [1.7320508 2.       ]]


In [44]:
v = np.array([9,10])
w = np.array([11,12])
print(v.dot(w))
print(np.dot(v,w))

219
219


In [45]:
print(k)
print(k.T)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]


### broadcasting